using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using Kronos.Data.GitHub;
using Kronos.Helpers;
using Xunit;

namespace Kronos.Tests;

/// <summary>
/// Guards the portable self-update, which replaces the running application with a downloaded file.
/// </summary>
/// <remarks>
/// This is the most dangerous code in the repository by consequence: a bug here does not produce a
/// wrong answer on screen, it produces an application that has overwritten itself with something
/// else, or that will not start afterwards.
///
/// The pure parts - asset selection and the script handed to the waiting helper - are asserted on
/// directly. The file-copying is done by that helper and cannot be asserted without launching one,
/// so what is checked here is that the script it is given says the right things.
/// </remarks>
public class PortableSelfUpdateTests
{
    static GitHubReleaseAsset Asset(string name, string digest = "sha256:abc123") => new()
    {
        Name = name,
        Digest = digest,
        State = "uploaded",
        Size = 1024,
        ContentType = "application/zip",
    };

    // ------------------------------------------------------------------ asset selection

    [Fact]
    public void ThePortableArchiveIsFoundByItsSuffix()
    {
        var assets = new[]
        {
            Asset("Kronos-1.53.0-portable.zip"),
            Asset("Kronos-1.53.0-installer.exe"),
            Asset("source.zip"),
        };

        Assert.Equal("Kronos-1.53.0-portable.zip", PortableSelfUpdate.FindPortableAsset(assets)?.Name);
    }

    [Fact]
    public void AnArchiveWithoutAChecksumIsRefusedRatherThanInstalledUnverified()
    {
        // The helper replaces the running application with whatever it is handed, so an unverifiable
        // download has no gate at all. Refusing is the only safe answer.
        var assets = new[] { Asset("Kronos-1.53.0-portable.zip", digest: "") };

        Assert.Null(PortableSelfUpdate.FindPortableAsset(assets));
    }

    [Fact]
    public void TwoArchivesAreRefusedBecauseThereIsNoWayToTellWhichIsMeant()
    {
        var assets = new[]
        {
            Asset("Kronos-1.53.0-portable.zip"),
            Asset("Kronos-1.53.0-preview-portable.zip"),
        };

        Assert.Null(PortableSelfUpdate.FindPortableAsset(assets));
    }

    [Fact]
    public void NoAssetsAtAllIsNotAnError()
    {
        Assert.Null(PortableSelfUpdate.FindPortableAsset(Array.Empty<GitHubReleaseAsset>()));
        Assert.Null(PortableSelfUpdate.FindPortableAsset(null!));
    }

    [Fact]
    public void AnInstallerAloneIsNotAPortableUpdate()
    {
        Assert.Null(PortableSelfUpdate.FindPortableAsset(new[] { Asset("Kronos-1.53.0-installer.exe") }));
    }

    // ------------------------------------------------------------------ handoff script

    [Fact]
    public void TheScriptWaitsForTheApplicationToExitBeforeTouchingAnything()
    {
        var script = PortableSelfUpdate.BuildHandoffScript(@"C:\tmp\extract", @"C:\apps\Kronos", 4321, relaunch: false);

        Assert.Contains("Wait-Process -Id 4321", script, StringComparison.Ordinal);
    }

    [Fact]
    public void TheScriptDoesNotNameItsWaitVariablePidBecauseThatIsAPowerShellAutomaticVariable()
    {
        // $PID holds the *script's own* process id. Shadowing it would make the script wait on itself,
        // forever, silently, after the app has already exited.
        var script = PortableSelfUpdate.BuildHandoffScript(@"C:\tmp\extract", @"C:\apps\Kronos", 4321, relaunch: false);

        Assert.DoesNotContain("$pid", script, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("$PID =", script, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void TheScriptBacksUpTheExecutableAndRestoresItIfTheCopyFails()
    {
        var script = PortableSelfUpdate.BuildHandoffScript(@"C:\tmp\extract", @"C:\apps\Kronos", 4321, relaunch: false);

        // The executable is the one file that cannot be re-obtained if the copy goes wrong.
        Assert.Contains("Copy-Item -LiteralPath $entry -Destination $backup", script, StringComparison.Ordinal);
        Assert.Contains("catch {", script, StringComparison.Ordinal);
        Assert.Contains("Copy-Item -LiteralPath $backup -Destination $entry", script, StringComparison.Ordinal);
        Assert.Contains("exit 1", script, StringComparison.Ordinal);
    }

    [Fact]
    public void TheScriptNeverCopiesTheUsersDataFolder()
    {
        // StoredData is AppContext.BaseDirectory/StoredData, so it sits in the very directory the update
        // writes into. The archive carries a blank database and default settings in it, generated by the
        // build's smoke test. Copying that over the installation wiped the user's game library and their
        // settings on every update. This is the guard for that.
        var script = PortableSelfUpdate.BuildHandoffScript(@"C:\tmp\extract", @"C:\apps\Kronos", 4321, relaunch: false);

        Assert.Contains($"$dataFolder = '{PortableSelfUpdate.DataFolderName}'", script, StringComparison.Ordinal);
        Assert.Contains("if ($relative.Split([char]'\\')[0] -eq $dataFolder) { return }", script, StringComparison.Ordinal);

        // The old line copied the whole tree, data folder included.
        Assert.DoesNotContain("Copy-Item -Path (Join-Path $kronosProcessId '*')", script, StringComparison.Ordinal);
    }

    [Fact]
    public void TheDataFolderNameMatchesTheOneStorageUses()
    {
        // A source scan rather than a reference, because Storage.StoragePath is only meaningful once the
        // app is running. If the two ever drift apart the updater starts overwriting user data again,
        // silently, and no other test would notice.
        var repositoryRoot = FindRepositoryRoot();
        var storage = File.ReadAllText(Path.Combine(repositoryRoot, "src", "Storage.cs"));

        Assert.Contains($"\"{PortableSelfUpdate.DataFolderName}\"", storage, StringComparison.Ordinal);
    }

    [Fact]
    public void TheScriptChecksTheExecutableWasActuallyReplacedRatherThanAssumingIt()
    {
        // The reported symptom: the update reported success, relaunched, and the About section still
        // showed the previous version, commit and build date. Nothing verified the copy had worked.
        var script = PortableSelfUpdate.BuildHandoffScript(@"C:\tmp\extract", @"C:\apps\Kronos", 4321, relaunch: false);

        Assert.Contains("Get-FileHash", script, StringComparison.Ordinal);
        Assert.Contains("$updated = $true", script, StringComparison.Ordinal);
    }

    [Fact]
    public void TheScriptKeepsGoingPastAFileItCannotWriteInsteadOfAbandoningTheUpdate()
    {
        // $ErrorActionPreference was 'Stop', which turned one locked file into a terminating error and
        // rolled the whole update back. The most commonly locked file - the SQLite database - is in the
        // folder now skipped, but anything else antivirus happens to hold must not stop the update.
        var script = PortableSelfUpdate.BuildHandoffScript(@"C:\tmp\extract", @"C:\apps\Kronos", 4321, relaunch: false);

        Assert.Contains("$ErrorActionPreference = 'Continue'", script, StringComparison.Ordinal);
        Assert.Contains("catch { [void]$failed.Add($relative) }", script, StringComparison.Ordinal);
    }

    [Fact]
    public void TheScriptRemovesTheRollbackCopyWhetherOrNotTheUpdateWorked()
    {
        // A failed update used to leave Kronos.exe.updatebak sitting in the installation forever.
        var script = PortableSelfUpdate.BuildHandoffScript(@"C:\tmp\extract", @"C:\apps\Kronos", 4321, relaunch: false);

        // Assert.True rather than Assert.Equal: with an int as the first argument this resolves to the
        // enumerable overload and fails to compile.
        Assert.True(
            CountOccurrences(script, "Remove-Item -LiteralPath $backup -Force") == 2,
            "The backup must be removed on both the success and the failure path.");
    }

    static int CountOccurrences(string haystack, string needle)
    {
        var count = 0;
        var index = 0;
        while ((index = haystack.IndexOf(needle, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += needle.Length;
        }

        return count;
    }

    static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "Kronos.sln")))
        {
            directory = directory.Parent;
        }

        Assert.NotNull(directory);
        return directory!.FullName;
    }

    [Fact]
    public void TheScriptRelaunchesTheApplicationOnlyWhenAskedTo()
    {
        Assert.Contains(
            "Start-Process -FilePath $entry",
            PortableSelfUpdate.BuildHandoffScript(@"C:\a", @"C:\b", 1, relaunch: true),
            StringComparison.Ordinal);

        Assert.DoesNotContain(
            "Start-Process -FilePath $entry",
            PortableSelfUpdate.BuildHandoffScript(@"C:\a", @"C:\b", 1, relaunch: false),
            StringComparison.Ordinal);
    }

    [Theory]
    // A single quote would otherwise end the string early and turn the rest of the path into code.
    [InlineData(@"C:\Users\O'Brien\Kronos", "O''Brien")]
    [InlineData(@"C:\Program Files\Kronos", "Program Files")]
    [InlineData(@"C:\apps\it's", "it''s")]
    public void PathsWithQuotesOrSpacesSurviveIntoTheScript(string path, string expected)
    {
        var script = PortableSelfUpdate.BuildHandoffScript(path, @"C:\target", 1, relaunch: false);

        Assert.Contains(expected, script, StringComparison.Ordinal);
    }

    [Fact]
    public void EveryPathAppearsInsideQuotes()
    {
        // Guards the class of bug where an unquoted path with a space silently becomes two arguments.
        var script = PortableSelfUpdate.BuildHandoffScript(@"C:\Program Files\source", @"C:\Program Files\target", 1, relaunch: false);

        Assert.Contains("'C:\\Program Files\\source'", script, StringComparison.Ordinal);
        Assert.Contains("'C:\\Program Files\\target'", script, StringComparison.Ordinal);
    }

    // ------------------------------------------------------------------ the real thing

    [Fact]
    public void TheArchiveLayoutIsWhatTheLocatorExpects()
    {
        // The build publishes Kronos.exe at the archive root. If that ever changes, the handoff would
        // copy a tree with no executable in it - so the shape is asserted against a real zip.
        var archive = Path.Combine(Path.GetTempPath(), $"kronos-test-{Guid.NewGuid():N}.zip");

        try
        {
            using (var stream = File.Create(archive))
            using (var zip = new ZipArchive(stream, ZipArchiveMode.Create))
            {
                var entry = zip.CreateEntry("Kronos.exe");
                using var writer = new StreamWriter(entry.Open());
                writer.Write("not a real executable");
            }

            var extracted = Path.Combine(Path.GetTempPath(), $"kronos-test-{Guid.NewGuid():N}");
            Directory.CreateDirectory(extracted);

            try
            {
                ZipFile.ExtractToDirectory(archive, extracted);

                // This mirrors what PrepareHandoff does to locate the payload root.
                var found = Directory
                    .EnumerateFiles(extracted, "Kronos.exe", SearchOption.AllDirectories)
                    .FirstOrDefault();

                Assert.NotNull(found);
                Assert.Equal(extracted, Path.GetDirectoryName(found));
            }
            finally
            {
                Directory.Delete(extracted, true);
            }
        }
        finally
        {
            File.Delete(archive);
        }
    }

    // ------------------------------------------------------- running the script for real

    /// <summary>
    /// A fake installation and a fake extracted update, laid out the way the real ones are.
    /// </summary>
    sealed class FakeInstall : IDisposable
    {
        public string Target { get; }
        public string Source { get; }
        readonly string _root;

        public FakeInstall()
        {
            _root = Path.Combine(Path.GetTempPath(), $"kronos-handoff-{Guid.NewGuid():N}");
            Target = Path.Combine(_root, "install");
            Source = Path.Combine(_root, "extracted");

            Directory.CreateDirectory(Target);
            Directory.CreateDirectory(Source);

            // What the user already has: an installed app and their data.
            Write(Target, "Kronos.exe", "OLD-EXE");
            Write(Target, "Kronos.dll", "OLD-DLL");
            Write(Target, "Assets/icon.ico", "OLD-ICON");
            Write(Target, "StoredData/kronos.db", "USER-DATABASE");
            Write(Target, "StoredData/json/settings.json", "USER-SETTINGS");

            // What the release archive holds: the new build, plus the blank data its smoke test created.
            Write(Source, "Kronos.exe", "NEW-EXE");
            Write(Source, "Kronos.dll", "NEW-DLL");
            Write(Source, "Assets/icon.ico", "NEW-ICON");
            Write(Source, "StoredData/kronos.db", "BLANK-DATABASE");
            Write(Source, "StoredData/json/settings.json", "DEFAULT-SETTINGS");
        }

        public string Read(string path) => File.ReadAllText(Path.Combine(Target, path));

        /// <summary>The script's own output, so a failure here says what PowerShell thought.</summary>
        public string Output { get; private set; } = string.Empty;

        /// <summary>Writes the generated script and runs it, returning its exit code.</summary>
        public int Run(bool relaunch = false)
        {
            var scriptPath = Path.Combine(_root, "handoff.ps1");
            File.WriteAllText(
                scriptPath,
                PortableSelfUpdate.BuildHandoffScript(Source, Target, processId: 0, relaunch));

            using var process = System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
            {
                FileName = "powershell.exe",
                Arguments = $"-NoProfile -NonInteractive -ExecutionPolicy Bypass -File \"{scriptPath}\"",
                UseShellExecute = false,
                CreateNoWindow = true,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
            })!;

            Output = process.StandardOutput.ReadToEnd() + process.StandardError.ReadToEnd();
            process.WaitForExit(120_000);
            Output += process.StandardOutput.ReadToEnd() + process.StandardError.ReadToEnd();

            return process.ExitCode;
        }

        static void Write(string root, string relativePath, string content)
        {
            var path = Path.Combine(root, relativePath.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, content);
        }

        public void Dispose()
        {
            try
            {
                Directory.Delete(_root, true);
            }
            catch (IOException)
            {
                // A leftover temp directory is not worth failing a test over.
            }
        }
    }

    [Fact]
    public void RunningTheScriptReplacesTheApplicationAndKeepsTheUsersData()
    {
        // This is the whole point of running it. Every other test here reads the script as text, which is
        // how a script that copies the database, or that restores the old executable and gives up, could
        // sit in the repository looking correct.
        using var install = new FakeInstall();

        var exitCode = install.Run();

        Assert.True(exitCode == 0, $"exit code was {exitCode}. Script output:\n{install.Output}");

        // The application is genuinely the new one...
        Assert.Equal("NEW-EXE", install.Read("Kronos.exe"));
        Assert.Equal("NEW-DLL", install.Read("Kronos.dll"));
        Assert.Equal("NEW-ICON", install.Read("Assets/icon.ico"));

        // ...and the user still has their library and their settings. Before the fix both of these came
        // back as BLANK-DATABASE and DEFAULT-SETTINGS, on every update, silently.
        Assert.Equal("USER-DATABASE", install.Read("StoredData/kronos.db"));
        Assert.Equal("USER-SETTINGS", install.Read("StoredData/json/settings.json"));
    }

    [Fact]
    public void RunningTheScriptLeavesNoRollbackCopyBehind()
    {
        using var install = new FakeInstall();

        install.Run();

        Assert.False(
            File.Exists(Path.Combine(install.Target, "Kronos.exe.updatebak")),
            "A failed update used to leave Kronos.exe.updatebak in the installation permanently.");
    }

    [Fact]
    public void RunningTheScriptStillUpdatesWhenOneFileCannotBeWritten()
    {
        // The regression behind the original report: a single locked file aborted the whole update, the
        // old executable was restored, and the About section went on reporting the previous version,
        // commit and build date with nothing on screen to say so.
        using var install = new FakeInstall();

        // Hold the installed executable open, exactly as a running or virus-scanned file would be.
        var lockedPath = Path.Combine(install.Target, "Kronos.exe");
        using (new FileStream(lockedPath, FileMode.Open, FileAccess.ReadWrite, FileShare.None))
        {
            var exitCode = install.Run();

            // Could not replace the executable, so it must not claim to have succeeded.
            Assert.Equal(1, exitCode);

            // But everything else was still copied, rather than the entire update being abandoned.
            Assert.Equal("NEW-DLL", install.Read("Kronos.dll"));
            Assert.Equal("NEW-ICON", install.Read("Assets/icon.ico"));

            // And the user's data is still theirs.
            Assert.Equal("USER-DATABASE", install.Read("StoredData/kronos.db"));
        }
    }
}
