; Kronos installer, Inno Setup 6.
;
; This replaces the NSIS script that used to live here. The reasons are worth recording, because
; most of them are not "Inno is nicer":
;
;   * NSIS cannot express a per user or per machine install from one installer without hand
;     wiring which registry hive and which shell folder each choice writes to. Every attempt ended
;     up duplicating that mapping, and the parts that were wrong compiled with zero warnings.
;   * The old script had no uninstaller of its own. It wrote an uninstall.log listing every path
;     as it went, and the uninstaller replayed that list. A file the app created afterwards was
;     left behind, and a file the app had already deleted made the uninstaller walk off the end.
;   * It needed a 757 line FileList.nsh generated by create_nsh_file_list.ps1 on every build, and
;     that file is not committed, so a build from a clean clone could not have reproduced it.
;
; Inno gives all of that for free: one [Files] entry with recursesubdirs instead of the generated
; list, a real uninstaller, and PrivilegesRequired=lowest with the "dialog" override, which is the
; supported way to ask "install for me or for everyone" and then put the folder, the registry hive
; and the Start Menu entry in the right place for the answer.
;
; The payload is unchanged. build_Installer.cmd still does the same dotnet publish, and the
; portable build is untouched.
;
; The product name is written out literally below rather than behind a #define. Inno's preprocessor
; only accepts quoted strings and numbers as define values, and a quoted name would then need
; splicing in "[Icons]" values such as {group}\"Kronos\", which is not worth the trouble. Only the
; version is worth sharing, because it also has to agree with ..\config.cmd and the csproj.

; Same version as <Version> in ..\src\Kronos.csproj and app_version in .\config.cmd. Passed in by
; package_Installer.cmd as /DAppVersion, so there is one place to change rather than three that
; have to agree. The literal below is only a fallback for running ISCC by hand.
#ifndef AppVersion
  #define AppVersion 1.48
#endif

[Setup]

; Stable across versions, so an upgrade finds and replaces the existing install instead of
; installing alongside it. Must not change, or every release becomes a second install.
AppId={{64E9E8E5-6CA2-41AE-896C-BBE9F1271B88}
AppName=Kronos
AppVersion={#AppVersion}

; Shown as the publisher in Windows "Installed apps". Kronos is not published by the original
; DLSS Swapper maintainer, so this must not name them.
AppPublisher=SpaceJamp

; Written to the uninstall registry entry's Comments value. Note this is NOT the same as the
; installer's own Properties, which is a common assumption and is wrong: verified against the built
; exe, AppComments does not reach it.
AppComments=Kronos is based on DLSS Swapper by beeradmoore, licensed under the GNU GPL v3.0.

; Version info on the installer's own exe, replacing the VIProductVersion and VIAddVersionKey calls
; in the old NSIS script. The app's file version comes from the csproj, not from here.
;
; GPL-3.0 requires the original copyright notices to be preserved, and the attribution is therefore
; carried in FileDescription rather than LegalCopyright. Inno Setup 6.7.3 has no directive for
; LegalCopyright or for Comments, which was checked by compiling each candidate rather than assumed:
; VersionInfoCompany, VersionInfoDescription and VersionInfoProductName are accepted, while
; VersionInfoLegalCopyright and a bare LegalCopyright are both rejected with "Unrecognized [Setup]
; section directive". FileDescription is the widest field that does reach Explorer's Properties, so
; that is where the credit goes.
VersionInfoVersion={#AppVersion}.0.0
VersionInfoProductVersion={#AppVersion}
VersionInfoCompany=SpaceJamp
VersionInfoProductName=Kronos
VersionInfoDescription=Kronos installer, based on DLSS Swapper by beeradmoore, GNU GPL v3.0

DefaultDirName={code:DefaultInstallDir}
DefaultGroupName=Kronos
UninstallDisplayName=Kronos
UninstallDisplayIcon={app}\Kronos.exe
DisableProgramGroupPage=yes

; There is deliberately no attempt to control the uninstall registry key name here. Inno Setup has
; no directive for it: UninstallKeyName, UninstallRegistryKey, AppUninstallKey, UninstallKey,
; UninstallSubkey and AppUninstallKeyName were each compiled and all six were rejected with
; "Unrecognized [Setup] section directive". The key name is always derived from AppId, which on a
; real install produced ...\Uninstall\{64E9E8E5-6CA2-41AE-896C-BBE9F1271B88}_is1.
;
; That is why src\App.xaml.cs locates its own entry by DisplayName across every hive and registry
; view instead of hard coding a path. Pinning the key name in the app, as the previous code did
; with ...\Uninstall\Kronos, was only ever working because the NSIS installer happened to agree.
;
; AppId still does its real job, which is telling Inno that a previous version of this product is
; already installed so an upgrade replaces it rather than sitting alongside it.

; Output is written to package\Output, where the build scripts expect it.
OutputDir=Output
OutputBaseFilename=Kronos-{#AppVersion}-installer
; lzma2/ultra64 on a self contained 300 MB publish is the difference between an installer that is
; pleasant to download and one that is not.
Compression=lzma2/ultra64
SolidCompression=yes

WizardStyle=modern
WizardSizePercent=110

; Install as a normal user by default, with no UAC prompt, because the default location is under
; %LOCALAPPDATA%\Programs and any user can write there. The "dialog" override is what puts the
; choice in front of the user; answering it for all users re-runs the installer elevated and
; switches every path, hive and shell folder to the machine wide equivalents. This is the part the
; NSIS script could not express.
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

; 64-bit only. Kronos.exe is built for win-x64 and will not run on 32-bit Windows, so refuse to
; install there rather than installing something that cannot start. "x64compatible" rather than
; "x64" throughout, which also keeps the installer running on Windows on ARM and avoids the
; deprecation warning ISCC emits for a bare "x64" in ArchitecturesInstallIn64BitMode.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0

SetupIconFile=..\src\Assets\icon.ico

; Shown on the page just before installing. Carries the GPL attribution, the modification notice and
; a pointer to the AI disclosure, which together are the notices this fork has to keep visible.
; Deliberately not LicenseFile=..\LICENSE: that is 34 KB of licence text in a scroll box on the
; welcome page, which trains people to click past the notices instead of reading them.
InfoBeforeFile=..\extras\installer_notices.txt

; Replaces the FindProcDLL plugin call the old script made at startup. Restart Manager notices that
; Kronos.exe has the files in {app} open, offers to close it, and carries on when it succeeds,
; instead of refusing to install at all and making the user hunt for the process.
CloseApplications=yes
RestartApplications=no

[Languages]
; English only, matching the old script's single MUI_LANGUAGE. Kronos itself is translated; the
; installer never was.
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; The whole publish directory in one entry, which is what recursesubdirs exists for. This replaces
; the generated FileList.nsh and the script that produced it. createallsubdirs is required alongside
; recursesubdirs or empty directories in the payload are skipped.
Source: "..\src\bin\publish\installer\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Icons]
Name: "{group}\Kronos"; Filename: "{app}\Kronos.exe"
Name: "{group}\Uninstall Kronos"; Filename: "{uninstallexe}"
Name: "{autodesktop}\Kronos"; Filename: "{app}\Kronos.exe"; Tasks: desktopicon

[Code]

/// <summary>
/// Default install folder, which depends on the scope the user chose at the start.
/// </summary>
/// <remarks>
/// Called for DefaultDirName, which is evaluated once the install mode is already settled, so
/// IsAdminInstallMode is meaningful here. The directory page still lets the user change it, and
/// Inno refuses to continue onto a folder that cannot be written to, which replaces the
/// .onVerifyInstDir writability probe the old script needed.
/// </remarks>
function DefaultInstallDir(Param: String): String;
begin
  if IsAdminInstallMode then
  begin
    Result := ExpandConstant('{autopf}\Kronos');
  end
  else
  begin
    Result := ExpandConstant('{localappdata}\Programs\Kronos');
  end;
end;

/// <summary>
/// Asks before uninstalling, and says what is about to go.
/// </summary>
/// <remarks>
/// Inno has its own confirmation page, but it does not know that the app keeps a database of
/// downloaded and imported DLSS files outside {app}, so the warning the old installer gave has to
/// be said somewhere. Returns False to cancel the uninstall.
/// </remarks>
function InitializeUninstall(): Boolean;
begin
  Result := MsgBox('Are you sure you want to uninstall Kronos?' + #13#10 + #13#10 +
    'This will also remove downloaded and imported files.' + #13#10 +
    'Changes to your games will remain as they are.',
    mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES;
end;

/// <summary>
/// Removes the app's data folder after a per user uninstall, and deliberately not after a machine
/// wide one.
/// </summary>
/// <remarks>
/// The data lives in %LOCALAPPDATA%\Kronos (Storage.StoragePath in ..\src\Storage.cs), so it is
/// per user even for a machine wide install, and any user can run the uninstaller. Deleting it
/// would destroy whoever happened to run the uninstall, while every other user on the machine
/// still had theirs. Inno removes {app} itself either way, which is all a machine wide uninstall
/// should take.
/// </remarks>
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep <> usPostUninstall then
  begin
    exit;
  end;

  if Pos(ExpandConstant('{localappdata}\'), Lowercase(ExpandConstant('{app}'))) <> 1 then
  begin
    exit;
  end;

  DelTree(ExpandConstant('{localappdata}\Kronos'), True, True, True);
end;
